apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook-web
        image: httpd
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: guestbook
    name: guestbook-service
spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
        app: guestbook
    type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: guestbook-ingress
spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: guestbook-service
              port:
                number: 8080
