apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guestbook
  name: guestbook-deploy
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: vitess/guestbook
        imagePullPolicy: Always
        name: guestbook
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: guestbook
  name: guestbook-svc
  namespace: test
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ing
  namespace: test
spec:
  ingressClassName: public
  rules:
  - host: jwi2.dk
    http:
      paths:
      - backend:
          service:
            name: guestbook-svc
            port:
              number: 80
        path: /
        pathType: Prefix
